package com.warehouse.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.biz.util.Utils;

/**
 * Entity mapped to table "AvgDB".
 */
public class AvgBean {

    private Long id;
    private String imgUrl;
    private String clickUrl;
    private Long startTime;
    private Long endTime;
    private Integer priority;
    private Long stopTime;

    public AvgBean() {
    }

    public AvgBean(Long id) {
        this.id = id;
    }

    public AvgBean(Long id, String imgUrl, String clickUrl, Long startTime, Long endTime, Integer priority, Long stopTime) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.clickUrl = clickUrl;
        this.startTime = startTime;
        this.endTime = endTime;
        this.priority = priority;
        this.stopTime = stopTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getClickUrl() {
        return clickUrl;
    }

    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Long getStopTime() {
        return stopTime==null||stopTime <= 0l ? 2000: stopTime;
    }

    public void setStopTime(Long stopTime) {
        this.stopTime = stopTime;
    }

}
