package com.warehouse.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ConfigDB".
 */
public class ConfigBean {

    private String id;
    private String type;
    private String cache;
    private String userId;
    private String key;
    private Long ts;

    public ConfigBean() {
    }

    public ConfigBean(String id) {
        this.id = id;
    }

    public ConfigBean(String id, String type, String cache, String userId, String key, Long ts) {
        this.id = id;
        this.type = type;
        this.cache = cache;
        this.userId = userId;
        this.key = key;
        this.ts = ts;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCache() {
        return cache;
    }

    public void setCache(String cache) {
        this.cache = cache;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Long getTs() {
        return ts;
    }

    public void setTs(Long ts) {
        this.ts = ts;
    }

}
