package com.warehouse.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.warehouse.dao.ConfigBean;
import com.warehouse.dao.AvgBean;
import com.warehouse.dao.OrderCartBean;
import com.warehouse.dao.MessageBean;

import com.warehouse.dao.ConfigBeanDao;
import com.warehouse.dao.AvgBeanDao;
import com.warehouse.dao.OrderCartBeanDao;
import com.warehouse.dao.MessageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configBeanDaoConfig;
    private final DaoConfig avgBeanDaoConfig;
    private final DaoConfig orderCartBeanDaoConfig;
    private final DaoConfig messageBeanDaoConfig;

    private final ConfigBeanDao configBeanDao;
    private final AvgBeanDao avgBeanDao;
    private final OrderCartBeanDao orderCartBeanDao;
    private final MessageBeanDao messageBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configBeanDaoConfig = daoConfigMap.get(ConfigBeanDao.class).clone();
        configBeanDaoConfig.initIdentityScope(type);

        avgBeanDaoConfig = daoConfigMap.get(AvgBeanDao.class).clone();
        avgBeanDaoConfig.initIdentityScope(type);

        orderCartBeanDaoConfig = daoConfigMap.get(OrderCartBeanDao.class).clone();
        orderCartBeanDaoConfig.initIdentityScope(type);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        configBeanDao = new ConfigBeanDao(configBeanDaoConfig, this);
        avgBeanDao = new AvgBeanDao(avgBeanDaoConfig, this);
        orderCartBeanDao = new OrderCartBeanDao(orderCartBeanDaoConfig, this);
        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);

        registerDao(ConfigBean.class, configBeanDao);
        registerDao(AvgBean.class, avgBeanDao);
        registerDao(OrderCartBean.class, orderCartBeanDao);
        registerDao(MessageBean.class, messageBeanDao);
    }
    
    public void clear() {
        configBeanDaoConfig.getIdentityScope().clear();
        avgBeanDaoConfig.getIdentityScope().clear();
        orderCartBeanDaoConfig.getIdentityScope().clear();
        messageBeanDaoConfig.getIdentityScope().clear();
    }

    public ConfigBeanDao getConfigBeanDao() {
        return configBeanDao;
    }

    public AvgBeanDao getAvgBeanDao() {
        return avgBeanDao;
    }

    public OrderCartBeanDao getOrderCartBeanDao() {
        return orderCartBeanDao;
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

}
