package com.warehouse.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_BEAN".
 */
public class MessageBean {

    private Long sysId;
    private Long id;
    private String userId;
    private String title;
    private String url;
    private String content;
    private Long createTime;
    private Boolean isRead;

    public MessageBean() {
    }

    public MessageBean(Long sysId) {
        this.sysId = sysId;
    }

    public MessageBean(Long sysId, Long id, String userId, String title, String url, String content, Long createTime, Boolean isRead) {
        this.sysId = sysId;
        this.id = id;
        this.userId = userId;
        this.title = title;
        this.url = url;
        this.content = content;
        this.createTime = createTime;
        this.isRead = isRead;
    }

    public Long getSysId() {
        return sysId;
    }

    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
