package com.warehouse.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDER_CART_BEAN".
 */
public class OrderCartBean {

    private Long id;
    private Long productId;
    private Long userId;
    private Integer count;
    private Long ts;

    public OrderCartBean() {
    }

    public OrderCartBean(Long id) {
        this.id = id;
    }

    public OrderCartBean(Long id, Long productId, Long userId, Integer count, Long ts) {
        this.id = id;
        this.productId = productId;
        this.userId = userId;
        this.count = count;
        this.ts = ts;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getTs() {
        return ts;
    }

    public void setTs(Long ts) {
        this.ts = ts;
    }

}
